version: '3'

services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - postgres
    volumes:
      - ./app:/srv/app
    networks:
      - code-network
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - dbvolume:/var/lib/postgresql/data
    networks:
      - code-network
    ports:
      - '5432:5432'

volumes:
  dbvolume:

networks:
  code-network:
    driver: bridge